=== JinSeok/crowd-ldap-plugin/src/main/resources/ldap.custom-attributes.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://ez.no/crowd/ldap.custom-attributes.xsd"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	targetNamespace="http://ez.no/crowd/ldap.custom-attributes.xsd">

	<xs:element name="custom-attributes">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="Directory" name="directory" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Directory">
		<xs:sequence>
			<xs:element name="server" maxOccurs="unbounded" type="xs:string" />
			<xs:element name="user" type="Attributes"/>
			<xs:element name="group" type="Attributes"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
 
	<xs:complexType name="Attributes">
		<xs:sequence>
			<xs:element name="attribute" type="Attribute" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Attribute">
		<xs:sequence>
			<xs:element name="ldap-name"  type="xs:string" />
			<xs:element name="format" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="pattern" type="xs:string" use="required" />
						<xs:attribute name="time-zone" type="xs:string" />
					</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" use="required" />
		<xs:attribute name="operational" type="xs:boolean" use="optional" />
		<xs:attribute name="type" default="STRING">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="STRING" />
					<xs:enumeration value="BINARY" />
					<xs:enumeration value="INTEGER" />
					<xs:enumeration value="DOUBLE" />
					<xs:enumeration value="DATETIME" />
					<xs:enumeration value="LOCAL_DATETIME" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

</xs:schema>

=== JinSeok/crowd-ldap-plugin/src/test/resources/ldap.custom-attributes-2.xml
<?xml version="1.0" encoding="UTF-8"?>

<custom-attributes 
	xmlns="http://ez.no/crowd/ldap.custom-attributes.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ez.no/crowd/ldap.custom-attributes.xsd http://ez.no/crowd/ldap.custom-attributes.xsd">
	
	<directory name="Community LDAP"> 
		<server>http://sdfasdf.no:8000</server>
		<server></server>
		<user>
			<attribute key="displayName" type="STRING">
				<ldap-name>displayName</ldap-name>
			</attribute>
			<attribute key="photo" type="BINARY">
				<ldap-name>jpegPhoto-updated</ldap-name>
			</attribute>
		</user>
		<group>
		</group>
	</directory>
</custom-attributes>

=== JinSeok/crowd-ldap-plugin/src/test/resources/ldap.custom-attributes-1.xml
<?xml version="1.0" encoding="UTF-8"?>

<custom-attributes 
	xmlns="http://ez.no/crowd/ldap.custom-attributes.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ez.no/crowd/ldap.custom-attributes.xsd http://ez.no/crowd/ldap.custom-attributes.xsd">
  	  
	<directory name="Community LDAP"> 
		<server>http://sdfasdf.no:8000</server>
		<server>123456789</server>
		<user>
			<attribute key="displayName" type="STRING">
				<ldap-name>displayName</ldap-name>
			</attribute>
			<attribute key="photo" type="BINARY">
				<ldap-name>jpegPhoto</ldap-name>
			</attribute>
			<attribute key="description" type="STRING">
				<ldap-name>description</ldap-name>
			</attribute>
			<attribute key="labeledURI" type="STRING">
				<ldap-name>labeledURI</ldap-name>
			</attribute>
			<attribute key="title" type="STRING">
				<ldap-name>title</ldap-name>
			</attribute>
			<attribute key="someInt" type="INTEGER">
				<ldap-name>int</ldap-name>
			</attribute>
			<attribute key="someDouble" type="DOUBLE">
				<ldap-name>double</ldap-name>
			</attribute>
			<attribute key="created" type="DATETIME" operational="true">
				<ldap-name>createTime</ldap-name>
			</attribute>
			<attribute key="createdXml" type="DATETIME">
				<ldap-name>created</ldap-name>
				<format pattern="yyyy-MM-dd'T'kk:mm:ssZ" time-zone="+01:00"/>
				<format pattern="yyyy-MM-dd'T'kk:mm:ss"/>
			</attribute>
		</user>
		<group>
			<attribute key="groupName" type="STRING">
				<ldap-name>displayName</ldap-name>
			</attribute>
			<attribute key="created" type="DATETIME" operational="true">
				<ldap-name>createTime</ldap-name>
			</attribute>
			<attribute key="modified" type="DATETIME" operational="true">
				<ldap-name>modifyTime</ldap-name>
			</attribute>
		</group>
	</directory>
</custom-attributes>
